### ISSUE TITLE
 Missing dll in build

### ISSUE THREAD

**Issue by mbround18** [warsnek/for-the-king-save-editor#1]
Hey i get a missing sql error on ur latest release, also a missing dll when running on master

Running from 1.1.2
![Annotation 2019-09-20 211633](https://user-images.githubusercontent.com/12646562/65367795-228de480-dbec-11e9-9c67-302a4698f4d2.png)

Running from master
![Annotation 2019-09-20 211633](https://user-images.githubusercontent.com/12646562/65367813-56690a00-dbec-11e9-8ebb-3743db626fa2.png)

**Comment by warsnek** [comment]
For the first exception could you get me a copy of your "player.db" ("C:\Users\[USERNAME]\AppData\LocalLow\IronOak Games\FTK\save\player.db") file, for some reason it seems to be structured differently from mine. Are you running the latest version of the game?

For the second exception, this looks like you didn't restore the NuGet package references of the project (you are missing the files from the SQLite nuget package).

**Comment by mbround18** [comment]
Latest revision from Microsoft Store

I did restore and i get the same issue, are you sure you included in the package file?


https://www.dropbox.com/s/ofyqjpj5bit1ahp/player.db?dl=0

**Comment by warsnek** [comment]
Yeah I just recloned the project to a new location on my machine and I did run into the same problem. I got it working by just running "Clean Solution" and the rebuilding. 
Not sure why that reference doesnt restore correctly the first time?

**Comment by warsnek** [comment]
Thanks for providing the player.db file, however my savegame editor works fine against that file, it has the same structure as mine. It certainly has the 'sPlayerStatistic' that your original error message is saying is missing. So yeah I am at a loss why that happenend.

Is this the 'player.db' you originally ran the editor on. or is this a new version after you deleted the file like you mentioned in your other issue?

**Comment by mbround18** [comment]
This is the original, i think what the issue is the game on steam stores it in the root folder but microsoft stores it in a .msstore[userid] folder

**Comment by warsnek** [comment]
So you are saying the player.db for the Microsoft store version is in a subfolder of the savegame folder (C:\Users\[username]\AppData\LocalLow\IronOak Games\FTK\save)?
I can make locating the file a bit more flexible then to solve this issue.

**Comment by warsnek** [comment]
I made a new release which might solve your problem (1.1.3).

**Comment by mbround18** [comment]
@warsnek your fix worked like a charm  👍 💯
