### ISSUE TITLE
A list of item codes for adding items to your inventory

### ISSUE THREAD

**Issue by swichers** [warsnek/for-the-king-save-editor#11]
I was unable to get your unpack/repack functionality to work for me, so I rolled my own using some shell scripting. While I was doing this I also took the time to get a list of (possible) item codes. I thought you might find the list useful:

https://github.com/swichers/for-the-king-save-utils/blob/main/ITEM-CODES.md

**Comment by warsnek** [comment]
This is known to me but I have no intention to expand on the functionality of the editor but thanks!
