### ISSUE TITLE
Doesnt add lore books

### ISSUE THREAD

**Issue by bradders098** [warsnek/for-the-king-save-editor#18]
when adding amount of lore books it doesnt add it to your character but everything else works :)

**Comment by warsnek** [comment]
This might be because there are multiple "lore" files in your savegame folder (epic has online/offline versions for example) and my tool is selecting the wrong version to edit, I just released version 1.2.1 of the editor where you now get to select the lore file to edit, see if that works for you!

**Comment by bradders098** [comment]
hi adding the lore points on the 2nd option on the drop down menu works now but when unlocking the lore shop items, once saving the file it crashes and doesnt work but when you unlock lore store on first option no items get unlocked so i can only use the longer save, great save editor and thank you.

**Comment by warsnek** [comment]
Can you make a screenshot of the error you get?

**Comment by bradders098** [comment]
![Screenshot_20210213-121702_Remote Desktop](https://user-images.githubusercontent.com/79006257/107849837-bc63bc00-6df5-11eb-94a7-6e518e847216.jpg)
![Screenshot_20210213-121739_Remote Desktop](https://user-images.githubusercontent.com/79006257/107849839-bf5eac80-6df5-11eb-8aa3-14537ebdf65c.jpg)
![Screenshot_20210213-121748_Remote Desktop](https://user-images.githubusercontent.com/79006257/107849843-c2599d00-6df5-11eb-9696-bd52c4fefb3c.jpg)


This is what is happening from start to finish
![Screenshot_20210213-121646_Remote Desktop](https://user-images.githubusercontent.com/79006257/107849836-b968cb80-6df5-11eb-96b4-009c2c931505.jpg)

**Comment by warsnek** [comment]
Thanks for the detailed information! So just to check, do you have the game running while using the savegame editor? Because it seems the lore file is in use and can therefore not be updated.
It might also be epic store that is keeping the file in use as epic might try to sync it to the cloud? Can you try again without epic running?

**Comment by bradders098** [comment]
With the epic games app closed and the game closed I am still getting an error
![Screenshot_20210213-123121_Remote Desktop](https://user-images.githubusercontent.com/79006257/107850052-77408980-6df7-11eb-81bd-aaa4830f020f.jpg)

**Comment by warsnek** [comment]
I might have some fixes that could work for you can you try if this version works: 
[ForTheKingSaveGameEditor.1.2.2.zip](https://github.com/warsnek/for-the-king-save-editor/files/5975643/ForTheKingSaveGameEditor.1.2.2.zip)

**Comment by bradders098** [comment]
Yes that works perfectly thank you

**Comment by warsnek** [comment]
Great!
