### ISSUE TITLE
Version 1.1.2 makes game unplayable

### ISSUE THREAD

**Issue by mbround18** [warsnek/for-the-king-save-editor#2]
When launching 1.1.2  and you hit the error in related issue it makes the game unplayable

**Comment by warsnek** [comment]
You could try going into your save folder and clear out the player.db file and optionally the .run files.
Save folder location: C:\Users\[username]\AppData\LocalLow\IronOak Games\FTK\save

**Comment by mbround18** [comment]
That didnt work but nuking my player.db did
