### ISSUE TITLE
y i cant select the save files .

### ISSUE THREAD

**Issue by Apathie** [warsnek/for-the-king-save-editor#20]
![image](https://user-images.githubusercontent.com/21095893/107849659-b55d9d80-6e37-11eb-8d7d-b0df11224b2c.png)

**Comment by Apathie** [comment]
![image](https://user-images.githubusercontent.com/21095893/107849733-3fa60180-6e38-11eb-8775-5c0216fbeb51.png)

**Comment by warsnek** [comment]
Do you have any save files? Can you make a zip of you savegame folder and upload it here, then I can take a look.
You can find your savegame folder here: C:\Users\[username]\AppData\LocalLow\IronOak Games\FTK\save

**Comment by Apathie** [comment]
[save.zip](https://github.com/warsnek/for-the-king-save-editor/files/5975635/save.zip)

**Comment by Apathie** [comment]
Only have player.db

**Comment by warsnek** [comment]
That is weird, but even when there are no savegame files (they end with the .run extension) it should just show an empty combobox and no exceptions. Are you using the latest version of the save game editor?

Did you start a game yet? If there should be savegame files they somehow must be located on a different location that my tool is using, if you can tell me where your savegame files for this game are being stored I could look into supporting it.

The savegame editor does already support loading savegame files from different location by specifing an alternate location as a parameter. Like this: 
ForTheKingSaveEdit.exe "c:\someotherlocation\save"

**Comment by Apathie** [comment]
C:\Users\pwwwl\AppData\LocalLow\IronOak Games\FTK\save\epic572c4abb002f4163a14178577d0f0300

**Comment by Apathie** [comment]
Maybe i always play with my friend and im not host .

**Comment by warsnek** [comment]
Yeah that might be it, don't see anything I can do about that sorry.

**Comment by Apathie** [comment]
![image](https://user-images.githubusercontent.com/21095893/107850763-d4602d80-6e3f-11eb-8b41-6ce61aed01b0.png)
   Yuh  It workd
