### ISSUE TITLE
1.2.1 crashes as pressing save and close

### ISSUE THREAD

**Issue by Christianwidjaya** [warsnek/for-the-king-save-editor#21]
The game is closed, and no other instances of save editor or the game running in background, double checked with resource monitor (not even suspended app)

images as follows
![image](https://user-images.githubusercontent.com/11766027/107850472-57c85180-6e35-11eb-9de6-c8e16214d710.png)

Happened when editing steam(userid number), not the default one.

Edit: Even I can delete the save manually when the save editor is closed

**Comment by warsnek** [comment]
I assume you are using the Epic version of the game right? Can you check if the file is not set to readonly?
Also can you confirm if it still happens with this version? 
[ForTheKingSaveGameEditor.1.2.2.zip](https://github.com/warsnek/for-the-king-save-editor/files/5975686/ForTheKingSaveGameEditor.1.2.2.zip)

**Comment by Christianwidjaya** [comment]
It works, I'm from the steam that talked with you earlier, closing this.

**Comment by warsnek** [comment]
Great, thanks for reporting it!
