### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by ItsMartinDuck** [warsnek/for-the-king-save-editor#22]
I did something with cheat engine and now I have -1294967617 lore and Its says that the value must be from minimal to maximal range. Am I doomed forever?

**Comment by warsnek** [comment]
I published a new version that might work for you, please try it [(Version 1.2.3)](https://github.com/warsnek/for-the-king-save-editor/releases/tag/1.2.3) and let me know if it worked for you?

If it still doesn't work make a screenshot of the error message, and add it here.
