### ISSUE TITLE
When I change character stats and gold it says there is a problem with the files

### ISSUE THREAD

**Issue by enejuto** [warsnek/for-the-king-save-editor#3]
I'm not much of a coder myself but I keep getting this message whenever I press 'Save & Close'
![image](https://user-images.githubusercontent.com/61654020/75625893-992f0500-5bc2-11ea-956e-d0c0aadd3fa8.png)

I press OK and It doesn't change anything in game

Thanks

**Comment by warsnek** [comment]
Hi MiniNox, seems your system is set up a bit more secure than mine :)
Have you tried running the save game editor as administrator? (right click on the ForTheKingSaveEdit.exe -> Run as Administrator). I think that should allow the savegame editor to save to that location. 
Also make sure your not running the game when you try to edit the savegame!

**Comment by enejuto** [comment]
Okay, I'll try

**Comment by enejuto** [comment]
Is there a way I can access the folders directly and change it from there?
[More where are the save game files located?]

**Comment by warsnek** [comment]
This is the location of the save folder:
%appdata%\\..\locallow\IronOak Games\FTK\save

**Comment by enejuto** [comment]
Thanks! 

But unfortunately, I don't know the codes
![image](https://user-images.githubusercontent.com/61654020/75626446-f24d6780-5bc7-11ea-9776-a220aa099f9f.png)

**Comment by enejuto** [comment]
Also If I change anything It will break my game, so it would be nice to know what im doing

**Comment by warsnek** [comment]
Yeah thats why you use the savegame editor, to make sense of that :)

Did running as administrator not work?

**Comment by enejuto** [comment]
No It didn't

**Comment by warsnek** [comment]
Ok, I can update the savegame editor with an option to select a different location to read and edit the savegames from, It would work like this:

1. Copy the contents savegame folder (%appdata%\\..\locallow\IronOak Games\FTK\save) to an alternate location like "c:\temp\ftksave"

2. Run the exe on the commandline with the alternate path like this:
      ForTheKingSaveEdit.exe "c:\temp\ftksave"

3. Edit and save some stuff

4. Copy the back from the temp location to the games savegame folder

Would that work for you? 

You need the [new version I just uploaded](https://github.com/warsnek/for-the-king-save-editor/releases/tag/1.1.5).

**Comment by enejuto** [comment]
I'll try it

Thanks!

**Comment by enejuto** [comment]
I've done as you said but it still doesn't work. I guess I will have to try this again later

Thanks for your time and effort

**Comment by enejuto** [comment]
Thanks I'll try this
