### ISSUE TITLE
Error when starting program

### ISSUE THREAD

**Issue by motornerve** [warsnek/for-the-king-save-editor#5]
![image](https://user-images.githubusercontent.com/18726973/78948859-9c00fd80-7a7e-11ea-86d4-36d44ccc6e96.png)

This error occurred when attempting to run the program today. It ran fine yesterday. I completely re-installed the program, but the issue persists.

**Comment by motornerve** [comment]
Did some digging with the help of my SDE Fiance and she found the issue here:

"ForTheKingSaveEdit/MainForm.cs
Line 38. Something weird breaks windows min and max if value is over 1000"

If the key for Lore Points goes over 1000, your program is not happy.

The key is STAT _LU_TOTAL_LORE in player.db

**Comment by warsnek** [comment]
Yeah figured that out myself, here is a fix: https://github.com/warsnek/for-the-king-save-editor/releases/tag/1.1.6

Thanks for reporting and taking the time to look into it!
