### ISSUE TITLE
I have trying to use it recently and have been struggling to change my lore. I have just been changing the value in the program with and without the game open, but it is not changing it.

### ISSUE THREAD

**Issue by MrProfishy** [warsnek/for-the-king-save-editor#7]

**Comment by warsnek** [comment]
Are you clicking "Save and close" after editing the value?

Also are you using the steam or epic version of the game? I use steam, so results may vary on the Epic version. For trouble shooting I would need you to zip your save game folder and upload it here. 
You can find the savegame folder in this location: "C:\Users\[username]\AppData\LocalLow\IronOak Games\FTK\save"

**Comment by KrosisXVI** [comment]
So the editor works great for all the statistics when targetting an Epic Games save file, but for some reason the lore never changes. I am not at home atm and can't provide a save file

**Comment by MrProfishy** [comment]
[save.zip](https://github.com/warsnek/for-the-king-save-editor/files/4552372/save.zip)
This is the zip file of my saves. KrosisXVI and I are one and the same and we have the same problem.

**Comment by MrProfishy** [comment]
Also I am on Epic games version.

**Comment by Francofly** [comment]
Same problem.Basically when you edit the save on epic games version,characters stats are saved but lore points and store unlocks don't.If you try and start the game offline everything saves.I think the issue comes when the epic launcher asks you if you want to upload the most recent save in the cloud or use an older one.If you upload the one you edited character stats will apply but lore and store unlocks won't.
Edit:I tried to disable cloud saves but that doesn't work either.

**Comment by warsnek** [comment]
> [save.zip](https://github.com/warsnek/for-the-king-save-editor/files/4552372/save.zip)
> This is the zip file of my saves. KrosisXVI and I are one and the same and we have the same problem.

Thanks for the zip, it explains why its not working. Your zip contains two folders "epic0" and "epic104543a9457e4767b2dd0e2d0b117bfc", each of those folders contains a "player.db" my tool takes the first player.db that it can find to edit the lore points.

I don't really know the significance of those folders but it seems the tool is editing the wrond player.db. So to work around it just rename the player.db file in the "epic0" folder then use my tool to edit the lore points and afterwards rename it back again.

Ill look into it later so my tool automatically selects the player.db which is not in the "epic0" folder if there are multiple.

**Comment by KrosisXVI** [comment]
Thanks Warsnek, this worked for me immediately.

**Comment by JanRK** [comment]
Works fine for me on Epic version, thanks!
